// var scale_list = {
//   "0":["awful vs. nice",
//   "little vs. big",
//   "slow vs. fast",
//   "sour vs. sweet",
//   "powerless vs. poweful",
//   "quiet vs. noisy"],
//   "1":[
//   "hellish vs. heavenly",
//   "shallow vs. deep",
//   "old vs. young",
//   "bad vs. good",
//   "weak vs. strong",
//   "dead vs. alive",
//   ],
//   "2":[
//   "mild vs. harsh",
//   "low vs. high",
//   "unknown vs. known",
//   "sad vs. happy",
//   "short vs. long",
//   "freezing vs. burning"
//   ],
// }
// var scale_list = {
// "0":[
// "ugly vs. beautiful",
// "yellow vs. blue",
// "hard vs. soft",
// "dirty vs. clean",
// "agitated vs. calm",
// "distasteful vs. tasty"],
// "1":[
// "worthless vs. valuable",
// "red vs. green" ,
// "cruel vs. kind" ,
// "soft vs. loud" ,
// "unpleasant vs. pleasant",
// "black vs. white" ],
// "2":[
// "bitter vs. sweet",
// "dull vs. sharp" ,
// "empty vs. full" ,
// "ferocious vs. peaceful",
// "light vs. heavy" ,
// "dry vs. wet" ],
// "3":[
// "profane vs. sacred" ,
// "tense vs. relaxed" ,
// "cowardly vs. brave" ,
// "poor vs. rich" ,
// "hazy vs. clear" ,
// "thin vs. thick" ],
// "4":[
// "dark vs. bright" ,
// "treble vs. bass" ,
// "rounded vs. angular",
// "foul vs. fragrant" ,
// "passive vs. active" ,
// "smooth vs. rough" ],
// "5":[
// "stale vs. fresh" ,
// "unfair vs. fair" ,
// "delicate vs. rugged",
// "bland vs. pungent" ,
// "sick vs. healthy" ,
// "narrow vs. wide"]
// }

// originally image_paths
var textures = [
  "P53",
  "P102",
  "P24",
  "P51",
  "P0",
  "P75",
  "P22",
  "G53",
  "G102",
  "G24",
  "G51",
  "G0",
  "G75",
  "G22",
  "S53",
  "S102",
  "S24",
  "S51",
  "S0",
  "S75",
  "S22",
  "F53",
  "F102",
  "F24",
  "F51",
  "F0",
  "F75",
  "F22",
  "M53",
  "M102",
  "M24",
  "M51",
  "M0",
  "M75",
  "M22",
];

var concept_conds = {
  0: ["dress", "pants", "shirt", "socks", "shoes"],
  1: ["blueberry", "lemon", "mango", "strawberry", "watermelon"],
  2: ["beach", "field", "ocean", "sky", "sunset"],
  3: ["angry", "disgust", "fearful", "happy", "sad"],
  4: ["above", "below", "beside", "near", "far"],
  5: ["dawn", "day", "dusk", "night", "noon"],
  6: ["bear", "bird", "lion", "frog", "fish"],
  7: ["airplane", "car", "boat", "truck", "train"],
  8: ["apple", "banana", "cherry", "grape", "peach"],

  9: ["carrot", "celery", "corn", "eggplant", "mushroom"],
  10: ["blizzard", "drought", "hurricane", "lightning", "sandstorm"],
  11: ["evil", "greed", "justice", "love", "peace"],
  12: ["driving", "eating", "sleeping", "leisure", "working"],
  13: ["comfort", "efficiency", "speed", "safety", "reliability"],
};
